kaliope <- readRDS("rds/22_Kalliope.csv.rds")
kaliope2 <- separateOnFilter(kaliope)
kaliope3 <- separateOnDate(kaliope2)
kaliope_C <- lapply(kaliope3, function(inner){ inner$Mag <- inner$Mag - min(inner$Mag)
return(inner)})
kaliope_r <- lapply(kaliope3[[2]], function(inner){ inner$Mag <- inner$Mag - min(inner$Mag)
return(inner)})
kaliope_v <- lapply(kaliope3[[3]], function(inner){ inner$Mag <- inner$Mag - min(inner$Mag)
return(inner)})
lapply(kaliope_C, function(inner){ggplot(inner, aes(x=Date,y=Mag))+geom_line()})
lapply(kaliope_r, function(inner){ggplot(inner, aes(x=Date,y=Mag))+geom_line()})
lapply(kaliope_v, function(inner){ggplot(inner, aes(x=Date,y=Mag))+geom_line()})
sapply(kaliope_v, function(inner){acf(inner$Mag,lag.max = 120)})

a <- sapply(kaliope_v, function(inner){acf(inner$Mag,lag.max = 120)})
b <- sapply(kaliope_v, function(inner){return(sum(max(inner$Date)-min(inner$Date))/length(inner$Date))})
for(i in 1:7) print(which.min(a[,i][[1]][,,])*b[i]*2*24)